env:
  browser: true
  es6: true
extends:
  - airbnb-base
  - prettier
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
plugins:
  - prettier
globals:
  createjs: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier:
    - error
  no-restricted-syntax:
    - error
    - selector: ForInStatement
      message: for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.
    - selector: LabeledStatement
      message: Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.
    - selector: WithStatement
      message: '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.'
  '@typescript-eslint/member-delimiter-style':
    - 2
    - multiline:
        delimiter: none
        requireLast: false
      singleline:
        delimiter: comma
        requireLast: false
  '@typescript-eslint/interface-name-prefix':
    - 2
    - prefixWithI: always
  curly:
    - error
  import/extensions:
    - 2
    - ignorePackages
    - js: never
      ts: never
  import/prefer-default-export:
    - 0
settings:
  import/resolver:
    node:
      paths:
        - src
      extensions:
        - .js
        - .ts
